#!/usr/bin/python
# -*- coding: iso-8859-1 -*-

# Author: Enrico Bocchi (Telecom ParisTech, Paris, 2015)


#-------------------------------------------------------------------------------
### Configuration parameters used in multiple scripts
#-------------------------------------------------------------------------------

# Input / Output file and folder names -- These are all relative paths
# Eventual headers are provided below the file name
LOGGER			= 'package_log.log'												# Log file for package generation

WEBPAGE_TREE	= 'webpage_tree'												# Destination folder for web objects

LAT_FILE_main	= 'RTT_Measurements.json'										# Latency json file generated by har_parser.py
LAT_FILE_es		= 'RTT_ExtremumSeeking.json'									# Latency json file generated by es.py

IF_SETT_FNAME	= 'server_ifaces.settings'										# Server interfaces settings filename
IF_SETT_HEADER	= "\t".join(["#iface", "ip_v4", "rtt", "loss"])					# Server interfaces settings header line

TMP_WEBPAGE		= '/tmp/tmpweb/'												# Temporary folder to relocate web objects
TAR_PACKAGE		= 'apache_package.tar.bz2'										# Filename (and extension) of the package
TAR_EXT			= '.tar.bz2'													# File extension of the output package

# Latency evaluation
LAT_RUNS = 10																	# Number of executing of the ping/paping command
LAT_PORT = 80																	# Preferred port for paping
LAT_PORT_secondary = 443														# Secondary port for paping

# Hosts file
HOSTS_FNAME	= 'hosts'															# Hosts file filename
BACKUP_NAME	= 'hosts.old'														# Backup name for the system hosts file
# TODO
''' Fix this to add 
	127.0.0.1	localhost
	127.0.1.1	user-VirtualBox
	in the case of Linux Mint '''
LOCAL_HOST	= "127.0.0.1 localhost"												# localhost line
LOCALH_ADDR	= "127.0.0.1"														# localhost IP address
LOCAL_HOSTv6= "\n".join([	"::1	localhost ip6-localhost ip6-loopback", \
							"fe00::0	ip6-localnet", \
							"fe00::1	ip6-mcastprefix", \
							"fe00::0	ip6-allnodes", \
							"fe00::0	ip6-allrouters", \
							"fe00::0	ip6-allhosts"])							# The following lines are desirable for IPv6 capable hosts


SERVER_ADDR = "137.194.164.56"													# First IP address available at the server side
																				# NOTE: we assume server IPs are consecutive
# IPv6 configuration
	# vous pouvez vous servir dans: 2001:660:330f:a4:1::/120
	# Prefix length	120
	# Network range 2001:660:330f:a4:1:0:0:0000 - 2001:660:330f:a4:1:0:0:00ff
	# Total IP addresses	256
IPv6_POOL	= "2001:660:330f:a4:1:0:0:"											# This is the network addess with last octet left empty
IPv6_H1		= 1																	# 1st address for HTTP/1.1 -- Last octet range: 0000:007f in hex -- 128 addresses
IPv6_H2		= 128																# 1st address for H2       -- Last octet range: 0080:00ff in hex -- 128 addresses

# Cross crypto parameters
CLEAR_OUTPUT	= 'clear'														# Package subfolder for content distribution over plain HTTP
ENCR_OUTPUT		= 'encrypted'													# Package subfolder for content distribution over SSL/TLS
HTTP			= 'http://'														# HTTP string
HTTPS			= 'https://'													# HTTPS string
HTTPS_PRIO		= "http/1.1 h2"													# Priority to HTTPS in virtualhost file
H2_PRIO			= "h2 http/1.1"													# Priority to H2 in virtualhost file
HTTP1			= "http/1.1"													# Serve only HTTP/1.1
H2				= "h2"															# Serve only H2
APACHE_TMP	= '/tmp/apache_tmp'													# Temporary folder for local deployment


# Local Apache deployment
APACHE_PORT	= "80"																# Default listening port
APACHE_PORT_secondary = "443"													# Alternate listening port for SSL/TLS
APACHE_ROOT	= '/tmp/apache'														# Folder for local website hosting
APACHE_SITE = '000-default.conf'												# 'sites-available' configuration file
LOCAL_DEPLOY_WARNINGS = "\n".join([	"*** PLEASE MOVE 'hosts' FILE FROM "+APACHE_ROOT+" TO /etc ***", \
									"*** PLEASE MOVE '"+APACHE_SITE+"'' FILE FROM "+APACHE_ROOT+" TO /etc/apache2/sites-available ***"])

# Server Apache deployment
SERVER_PORT	= "80"																# Default listening port
SERVER_PORT_secondary = "443"													# Alternate listening port for SSL/TLS
SERVER_HOSTFILES = 'virtual_hosts'												# 'sites-available' configuration file
SERVER_ROOT	= '/home/server/apache2-00'											# Apache root folder on the server side
SERVER_CONF = '/etc/apache2-00'													# Installation folder of Apache server
																				# NOTE: for both SERVER_ROOT and SERVER_CONF,
																				# the server number has to be appended after '-00'
